### ISSUE TITLE
PC Version

### ISSUE THREAD

**Issue by Noxalus** [GovanifY/KH1FM_Toolkit#1]
Hello,

Kingdom Hearts HD 1.5+2.5 ReMIX will be released on PC (through the Epic Games Store) the next week, and like the original one (Kingdom Hearts HD 1.5), we won't have VF.

I know that the KH1FM_Toolkit can be used to add VF to the Final Mix version of Kingdom Hearts, and I would like to know if there is a chance for this project to work with the future PC version.

It's probably a dumb question as we can't know how game files look until we can download the game (so after its release on EGS), but I would like to know if you have some hint.

Do you plan to work on a patch for french voices with the PC version?

Thanks a lot in advance for your answer!

**Comment by GovanifY** [comment]
I am not planning to work on Kingdom Hearts in the future.

If the PC port are no different from the HD remixes then the files are hashed with truncated md5 this time around, without compression, and when extracted contain the original files and optional "HD headers". Those HD headers contain files that are loaded instead of the original by the remixes, say HD textures. This allows them to keep everything else working as intended.

With that said you can get HD remixes benefits in PCSX2 by getting a 60FPS patch, the custom music tool Xaddgx is developing and texture replacement to get the same experience, so I don't see a personal reason to be this hyped about PC releases, this won't help modding anymore than the state at which it is now/

**Comment by Noxalus** [comment]
Thank you for the answer!

I will try do a VF patch myself when the game will be released, thank you so much for sharing the source of your toolkit, I think it will be a great help to do that quickly!

**Comment by Noxalus** [comment]
The game has finally been released a few hours ago and from what I saw from now, most of the files have been packaged in a few files:

![image](https://user-images.githubusercontent.com/1321964/113045155-c6236200-919e-11eb-9985-8647a191fb56.png)

Cinematics seem to be in another folder:

![image](https://user-images.githubusercontent.com/1321964/113045225-dcc9b900-919e-11eb-96c7-539cfad658f7.png)

I won't bother you after this message, but do you have any idea of what could be HED and PKG file format? Do you know how I could extract (and compress again) the content from them?

Do you know a someone (or a community) that could help me in this task?

**Comment by GovanifY** [comment]
Unfortunately, I don't think I'm going to be involved with the Kingdom Hearts community in any fashion anymore. 
As I haven't looked at those files, I do not know what they contains.

The only community I can recommend you is OpenKH but they have a bad habit of remaking tools worse off than they were 10 years ago, so you'll have to see how this turns out. 
They also have been openly hostile to projects such as PCSX2, friends of my own and myself, so I'd rather not get involved in any fashion with them.
